get_cars:
    path: /cars
    controller: App\Controller\CarsController::getCars
    methods: GET
    
credit:
    path: /suitable_credit
    controller: App\Controller\CreditController::getSuitableCredit
    methods: GET

apply:
    path: /apply
    controller: App\Controller\CreditApplicationController::apply
    methods: POST 
       
admin:
    resource: 'admin/routes_admin.yaml'
    prefix: "/admin"
